module RenderingLevels
  RESERVED_ASTEROID_LEVELS = [1, 4, 6, 8, 10]
  BACKGROUND = 0
  GROUND = 2
  PLATFORM_BACKGROUND = 3
  PLAYER1 = 5
  PLAYER2 = 7
  PLATFORM = 9

  attr_reader :RESERVED_ASTEROID_LEVELS, :BACKGROUND, :GROUND, :PLATFORM_BACKGROUND, :PLAYER1, :PLAYER2, :PLATFORM

end