module RenderingLevels
  BACKGROUND ||= 0
  ASTEROID_BACKGROUND ||= 1
  GROUND ||= 2
  PLATFORM_BACKGROUND ||= 3
  ASTEROID_INTERACTIVE ||= [4, 6, 8, 10]
  PLAYER1 ||= 5
  PLAYER2 ||= 7
  PLATFORM ||= 9

  LEVELS ||= 10

  attr_reader :RESERVED_ASTEROID_LEVELS, :BACKGROUND, :GROUND, :PLATFORM_BACKGROUND, :PLAYER1, :PLAYER2, :PLATFORM, :LEVELS

end