module RenderingLevels
  attr_reader :BACKGROUND, :ASTEROID_BACKGROUND, :GROUND, :PLATFORM_BACKGROUND, :ASTEROID_INTERACTIVE, :PLAYER1, :PLAYER2, :PLATFORM, :LEVELS
  BACKGROUND ||= 0
  ASTEROID_BACKGROUND ||= 1
  GROUND ||= 2
  PLATFORM_BACKGROUND ||= 3
  ASTEROID_INTERACTIVE ||= [4, 6, 8, 10]
  PLAYER1 ||= 5
  PLAYER2 ||= 7
  PLATFORM ||= 9
  LEVELS ||= 11
end